test
bglgwyng/ts-snippets pull request #2
Opened 2024-04-11 11:11 UTC by ireh1214

@f-lab-jake 

test

2024-04-15 10:48 UTC, f-lab-jake reviewed
멘토링때 이야기 했던 내용들과 포매팅 적용해서 다시올려주세요.

2024-04-16 12:30 UTC, ireh1214 commented
@f-lab-jake
다시 올렸습니다! 
biome 플러그인으로 포맷팅을 적용하였고 js를 타입스크립트로 바꿔보았습니다

2024-04-20 03:18 UTC, f-lab-jake requested changes

2024-04-20 03:18 UTC, f-lab-jake commented on LV0/test4.ts
>  	return answer;
더 줄여보세요

2024-04-26 07:16 UTC, closed without merging